/*
  THIS FILE IS AUTO-GENERATED by hybrid-render extension of Quasar.
  You should not temper with this file, unless really needed.
*/

const swrChecks = new Map();

const runtime = { swrChecks };

module.exports = { runtime };
